import { Kysely, sql } from 'kysely'

// rate_limit_config was a literal one-row singleton (id checked to always
// equal 1) shared by every organization — one org's admin adjusting send
// rate limits, delay windows, or the paused flag silently affected every
// other organization's outgoing sends. This gives every organization its own
// independent config row, seeded from whatever the shared row held today so
// no org's effective limits change at migration time.
export async function up(db: Kysely<any>): Promise<void> {
  // The `id = 1` check was auto-named by Postgres when the table was created
  // (no explicit name given) — look it up rather than hardcoding the name,
  // in case Postgres's default naming ever differs.
  const checks = await sql<{ conname: string }>`
    select conname from pg_constraint where conrelid = 'rate_limit_config'::regclass and contype = 'c'
  `.execute(db)
  for (const row of checks.rows) {
    await sql`alter table rate_limit_config drop constraint ${sql.ref(row.conname)}`.execute(db)
  }

  // Give `id` a real sequence (starting after the existing singleton row) so
  // future per-org rows don't need to invent their own id.
  await sql`alter table rate_limit_config alter column id add generated by default as identity (start with 2)`.execute(db)

  await db.schema
    .alterTable('rate_limit_config')
    .addColumn('organization_id', 'integer', (col) => col.references('organizations.id').onDelete('cascade'))
    .execute()

  const shared = await db.selectFrom('rate_limit_config').selectAll().where('id', '=', 1).executeTakeFirst()
  const organizations = await db.selectFrom('organizations').select('id').execute()

  if (shared) {
    for (const org of organizations) {
      await db
        .insertInto('rate_limit_config')
        .values({
          organization_id: org.id,
          max_per_minute: shared.max_per_minute,
          max_per_hour: shared.max_per_hour,
          min_delay_ms: shared.min_delay_ms,
          max_delay_ms: shared.max_delay_ms,
          concurrency: shared.concurrency,
          pause_after_consecutive_failures: shared.pause_after_consecutive_failures,
          is_paused: shared.is_paused
        })
        .execute()
    }

    // The old shared row is now superseded by one independent copy per
    // organization above — remove it so it doesn't sit around unused (and
    // unreachable, since every query from here on filters by organization_id).
    await db.deleteFrom('rate_limit_config').where('id', '=', 1).execute()
  }

  await db.schema.alterTable('rate_limit_config').addUniqueConstraint('rate_limit_config_organization_id_key', ['organization_id']).execute()
}

export async function down(db: Kysely<any>): Promise<void> {
  await db.schema.alterTable('rate_limit_config').dropConstraint('rate_limit_config_organization_id_key').execute()
  await db.schema.alterTable('rate_limit_config').dropColumn('organization_id').execute()
  await sql`alter table rate_limit_config alter column id drop identity if exists`.execute(db)
  await db.schema.alterTable('rate_limit_config').addCheckConstraint('rate_limit_config_id_check', sql`id = 1`).execute()
}
