import { Kysely, sql } from 'kysely'

// task_settings was a literal one-row singleton (id checked to always equal
// 1) shared by every organization — one org's admin changing working hours,
// reminder timing, or auto-report/digest schedules silently reconfigured
// every other organization's tasks. This gives every organization its own
// independent settings row, seeded from whatever the shared row held today
// so no org's effective schedule changes at migration time.
export async function up(db: Kysely<any>): Promise<void> {
  const checks = await sql<{ conname: string }>`
    select conname from pg_constraint where conrelid = 'task_settings'::regclass and contype = 'c'
  `.execute(db)
  for (const row of checks.rows) {
    await sql`alter table task_settings drop constraint ${sql.ref(row.conname)}`.execute(db)
  }

  await sql`alter table task_settings alter column id add generated by default as identity (start with 2)`.execute(db)

  await db.schema
    .alterTable('task_settings')
    .addColumn('organization_id', 'integer', (col) => col.references('organizations.id').onDelete('cascade'))
    .execute()

  const shared = await db.selectFrom('task_settings').selectAll().where('id', '=', 1).executeTakeFirst()
  const organizations = await db.selectFrom('organizations').select('id').execute()

  if (shared) {
    for (const org of organizations) {
      await db
        .insertInto('task_settings')
        .values({
          organization_id: org.id,
          working_hours_start: shared.working_hours_start,
          working_hours_end: shared.working_hours_end,
          auto_report_daily_enabled: shared.auto_report_daily_enabled,
          auto_report_daily_time: shared.auto_report_daily_time,
          auto_report_weekly_enabled: shared.auto_report_weekly_enabled,
          auto_report_weekly_day: shared.auto_report_weekly_day,
          auto_report_weekly_time: shared.auto_report_weekly_time,
          auto_report_monthly_enabled: shared.auto_report_monthly_enabled,
          auto_report_monthly_day: shared.auto_report_monthly_day,
          auto_report_monthly_time: shared.auto_report_monthly_time,
          reminder_daily_time: shared.reminder_daily_time,
          daily_overview_enabled: shared.daily_overview_enabled,
          daily_overview_time: shared.daily_overview_time,
          weekly_report_enabled: shared.weekly_report_enabled,
          weekly_report_day: shared.weekly_report_day,
          weekly_report_time: shared.weekly_report_time,
          review_digest_enabled: shared.review_digest_enabled,
          review_digest_time: shared.review_digest_time
        })
        .execute()
    }

    await db.deleteFrom('task_settings').where('id', '=', 1).execute()
  }

  await db.schema.alterTable('task_settings').addUniqueConstraint('task_settings_organization_id_key', ['organization_id']).execute()
}

export async function down(db: Kysely<any>): Promise<void> {
  await db.schema.alterTable('task_settings').dropConstraint('task_settings_organization_id_key').execute()
  await db.schema.alterTable('task_settings').dropColumn('organization_id').execute()
  await sql`alter table task_settings alter column id drop identity if exists`.execute(db)
  await db.schema.alterTable('task_settings').addCheckConstraint('task_settings_id_check', sql`id = 1`).execute()
}
